node:
  build: .
  command: "node ./index.js | ./node_modules/.bin/bunyan"
  environment:
    APPLICATION_ENV: development
    APP_PORT: 3000
  ports:
    - "14200:3000"
  volumes:
    - ./src:/var/www/src
    - ./config:/var/www/config
    - ./data:/var/www/data
    - ./package.json:/var/www/package.json
    - ./index.js:/var/www/index.js
